### ISSUE TITLE
add logo

### ISSUE THREAD

**Issue by petermeissner** [rusershamburg/rusershamburg.github.io#1]

**Comment by henningsway** [comment]
Ich glaub, dass sieht man gerade nicht. Kannst du mal schauen? :)

**Comment by petermeissner** [comment]
Jip, ist nicht da ... Muss ich rein schauen.

Henning <notifications@github.com> schrieb am Sa., 19. Mai 2018, 11:59:

**Comment by petermeissner** [comment]
fixed in: 6126d133408199afab9b26506a9f52d49dd6ad7b
