### ISSUE TITLE
add some meeting statistics to front page

### ISSUE THREAD

**Issue by petermeissner** [rusershamburg/rusershamburg.github.io#11]
- n group memers
- n last meeting
- ... ???

**Comment by petermeissner** [comment]
- automatically adding data to the repo each day - done, works ✔️ 
- showing stats as graphics - done, works ✔️ 

... I leave this issue open a little longer until everyone had a first glance at the graphics ... I kind of played it very down with mute colors taken from the banner image ... feel free to criticise 💬

**Comment by Tazinho** [comment]
Nice! I just looked at it for the first time. My first impression would be that the graphics would be better under the text. However, as these seem to be R-Graphics embedded into Markdown there is a lot of potential and I am sure that with time and when the site is a bit more established a lot more ideas will come up for graphics in general.

**Comment by petermeissner** [comment]
- I put them under the text ✔️ 

The graphics are neither R nor Markdown. I used d3.js:

- line 147ff of the source code of: https://rusershamburg.github.io/ (or that one: https://github.com/rusershamburg/rusershamburg.github.io/blob/master/_includes/meetup_group_stats.html)
- https://rusershamburg.github.io/assets/js/ts_plot.js
- https://rusershamburg.github.io/assets/js/ts_plot_event_handler.js
