### ISSUE TITLE
add possibility to join slack channel as icon on the website

### ISSUE THREAD

**Issue by henningsway** [rusershamburg/rusershamburg.github.io#12]
It would be nice if website-visitors could self-join https://friendswithdata.slack.com/messages/CA65MTQJU/

Maybe https://github.com/rauchg/slackin is a solution here? It seems to require a webserver though?

Resource:
https://www.quora.com/Is-there-a-way-to-enable-anyone-to-join-a-Slack

**Comment by petermeissner** [comment]
After first glance: hmmm, for this a server is needed :-(

**Comment by Tazinho** [comment]
I think it would be cool if we just link the slack and add an email to ask for the invitation like the mlr guys do also.. see: https://github.com/mlr-org/mlr

**Comment by petermeissner** [comment]
Sounds good.

Do we put it into the description of the meetup page (this will then automatically propagate to the webpage) or should we put the link and description extra?

**Comment by Tazinho** [comment]
You catch the results from the meetup page!? Really cool!

@henningsway is it ok if I add the slack + your E-Mail address for invitation to the meetup page, since you are the founder of the slack channel?

**Comment by petermeissner** [comment]
Jip, sure do ... you change it on meetup - its live on webpage (You said "Webpage should be no overhead for organizers." ... so tha is what you get )

You put up a new event on meetup it should be on the front page of the webpage asap.

**Comment by Tazinho** [comment]
I like :) It's funny that it looks even better on the webpage since meetup seems to have a problem with hyperlinks...I used their tool for the formatting, but they still just show the plain text instead of the markup...

I hope we can test the new meetup mirroring option soon :)

**Comment by henningsway** [comment]
I am not super fond of my private email being on the frontpage of the meetup-site, but for now I think it is okay. I would much prefer a more automatic solution, but let's do it like this for now.

Thank you for your work and thoughts.

**Comment by henningsway** [comment]
Hey Peter,

können wir evtl. oben rechts auf der Webseite ein Slack-Icon einfügen, das dann auf eine Unterseite führt, wo der Link zum Channel (Datafriends) und meine E-mailadresse für die Einladung führt?

Dann wären die Icons vollständig und meine E-mail-Adresse würde von der Frontpage verschwinden. :)

LG und vielen Dank! Bis bald

**Comment by petermeissner** [comment]
Müsste gehen, Guck ich mir bei Gelegenheit an .

Henning <notifications@github.com> schrieb am Sa., 19. Mai 2018, 11:58:

**Comment by petermeissner** [comment]
Ok, ich hätte ne Alternative: Ein kleines Formular, dass eine Mail an deine Adresses mit Name, Email und der Bitte um Freischaltung enthält?

**Comment by petermeissner** [comment]
so ...
- icon ✔️ 
- **hennings mail ist jetzt überflüssig** ✔️ - wenn das Icon anklickt kann man ein Formular ausfüllen und Henning bekommt eine Email von **bot@petermeissner.de** (wahrscheinlich landet sie erstmal im Spam, also aufpassen ... ich bin aber auch noch im CC also sollte erstmal nix verlorengehen)

**Comment by henningsway** [comment]
komisch, bisher nicht. kannst du es nochmal senden?

**Comment by petermeissner** [comment]
Im spam?, Probier's Mal selber aus, auf der Seite ... Ich gucke, ob ich's
bekomme.

Henning <notifications@github.com> schrieb am Fr., 25. Mai 2018, 17:23:

**Comment by petermeissner** [comment]
Hey, ich habe nochmal zwei Anfragen bekommen - ich nehme an, dass du die ausgefüllt hast - oder ?

**Comment by petermeissner** [comment]
Hmmm, Vorschlag: wir stellen schonmal um - bei mir kommen die Sachen an -
und bis auf weiteres leite ich anfragen weiter - meine Mails bekommst du ja
auch. Sicher, dass es nicht im Spam hängen geblieben ist?

Henning <notifications@github.com> schrieb am Sa., 26. Mai 2018, 10:24:

**Comment by henningsway** [comment]
klingt gut. Einen Spamordner gibt es wohl bei Posteo nicht.  Ich weiß echt nicht, was da noch schieflauen könnte...

https://posteo.de/hilfe/wie-funktioniert-der-posteo-spamfilter

**Comment by Tazinho** [comment]
Habe jetzt mal die E-Mail Adresse auf der Meetupseite ausgetauscht.

Wie ist der Stand mit dem Launch Item auf der Homepage? Habe gerade eine Testanfrage gestartet. Ich würde sagen, wenn du die sehen kannst @petermeissner kann hier zu. Oder?

**Comment by petermeissner** [comment]
Hey, jip, ich bekomme ne Benachrichtigung wenn jemand auf den Sack möchte.

Malte Grosser <notifications@github.com> schrieb am Mo., 22. Juli 2019,
16:01:

**Comment by Tazinho** [comment]
Ausgezeichnet.
