### ISSUE TITLE
Add email address

### ISSUE THREAD

**Issue by Tazinho** [rusershamburg/rusershamburg.github.io#13]
Maybe we should create a general email address for the user group.

What do you think @petermeissner @henningsway @rappster 
We could redirect it to all organizers, use it for the slack channel invitation and general questions. We could also display it at the top icon bar.

**Comment by henningsway** [comment]
this is a very nice idea. who would host us? @rbind.io or similar would be really cool. :)

**Comment by henningsway** [comment]
lets stick to "rusershamburg" to be consistent with our other channels. Even though it is a little longer, its more explicit and that is always good. :)

**Comment by rappster** [comment]
rusershamburg@rbind.io would be rad

Sent from my smartphone

Henning <notifications@github.com> schrieb am Sa., 5. Mai 2018, 17:34:

**Comment by Tazinho** [comment]
@petermeissner Könntest du info@rusershamburg einrichten? Wir können dann von dort an alle Organisatoren weiterleiten.

**Comment by petermeissner** [comment]
Ich schaue mich mal nach Optionen um.

Am Fr., 21. Dez. 2018 um 15:14 Uhr schrieb Tazinho <notifications@github.com

**Comment by petermeissner** [comment]
![image](https://user-images.githubusercontent.com/939139/50520176-20648280-0abf-11e9-8360-f9907f0f86a9.png)

**Comment by Tazinho** [comment]
Würde gehen. (und ich wäre dafür). Andere Vorschläge, Einwände?

**Comment by petermeissner** [comment]
Ich gucke Mal noch weiter, wäre jetzt Mal eine Möglichkeit.

PS.: Die Domain Hamburgr.org ist noch frei ... Wäre etwas kürzer als
Rusershamburg.org oder Rusershamburg.de.

Am Fr., 28. Dez. 2018, 16:53 hat Tazinho <notifications@github.com>
geschrieben:

**Comment by Tazinho** [comment]
Ich glaube dann bräuchten wir ein weiters Issue. Letztlich muss der Name zwischen Github, Domain, E-Mail, Twitter und Youtube Konsistent sein.

**Comment by petermeissner** [comment]
Guter Punkt.

Am Fr., 28. Dez. 2018, 17:21 hat Tazinho <notifications@github.com>
geschrieben:

**Comment by petermeissner** [comment]
Noch ein Angebot von 1&1, allerdings mit 12 Monate Laufzeit 

![image](https://user-images.githubusercontent.com/939139/50585192-1c947f80-0e74-11e9-9e89-a593f906a539.png)

**Comment by petermeissner** [comment]
Noch eine Variante von Strato: 12 Monate Laufzeit; 

Summe 1 Jahr: 23,20 €
Summe 2 Jahre: 32,20 €
Summe 3 Jahre: 41,20 €

![image](https://user-images.githubusercontent.com/939139/50585536-c45e7d00-0e75-11e9-97e0-c077c439b6cb.png)

**Comment by petermeissner** [comment]
PS.: Noch zu recherchieren https://support.rbind.io/about/

**Comment by petermeissner** [comment]
❌ rbind liefert keine Domains und kein Emailhosting

**Comment by Tazinho** [comment]
Zusammengefasst:

**Strato, 1 Monatige Laufzeit dafür ne Einrichtungsgebühr von 15 Euro.**

Summe 1 Jahr: 25,40 €
Summe 2 Jahre: 45,80 €
Summe 3 Jahre: 71,20 €

**Noch ein Angebot von 1&1, allerdings mit 12 Monate Laufzeit**

Summe 1 Jahr: 12 €
Summe 2 Jahre: 36 €
Summe 3 Jahre: 60 €

**Nochmal Strato (12 Monate Laufzeit)**
Summe 1 Jahr: 23,20 €
Summe 2 Jahre: 41,20 €
Summe 3 Jahre: 59,20 €

**Comment by Tazinho** [comment]
Sieht für mich aus als sei das dritte (Strato - 12 Monate Laufzeit) am besten, wenn wir damit länger als 2,xx Jahre glücklich sind (das erste von Strato können wir eh ausschließen oder? Und ggü. 1 & 1 sparen wir ab Jahr 2,xx 6€ / Jahr). Wenn du damit happy wärst, Peter (du bist schließlich unser Webdeveloper) würde ich das befürworten.

**Comment by petermeissner** [comment]
Jip, sehe ich auch so.

Am Mi., 2. Jan. 2019 um 13:06 Uhr schrieb Tazinho <notifications@github.com

**Comment by petermeissner** [comment]
Hallo Zusammen,

ich wollte das Thema nochmal aufgreifen und dann auch abschließen. Ich
würde jetzt schauen, das ich die Domain "*rusershamburg.org
<http://rusershamburg.org>*" ergattere. Dazu gibt es dann
Emailadressen wie *info@rusershamburg.org
<info@rusershamburg.org>*.

Passt das für alle?


LG Peter





Am Mi., 2. Jan. 2019 um 20:58 Uhr schrieb Peter Meissner <
retep.meissner@gmail.com>:

**Comment by Tazinho** [comment]
Von meiner Seite sehr gerne. Danke @petermeissner !

**Comment by Tazinho** [comment]
So, es sieht aus als wären wir mit dem Thema durch und hier kann dicht. Bzgl. der Kosten müssen wir uns an anderer Stelle nochmal austauschen, @petermeissner.

@henningsway @rappster @strengejacke falls ihr mal eine RUsers-Email benötigt, geht gerne auf Peter zu.

**Comment by strengejacke** [comment]
Kostet doch nichts, oder? Kann ja an mail@danielluedecke.de weiterleiten.
