### ISSUE TITLE
Welche Web- und Emaildomain?

### ISSUE THREAD

**Issue by petermeissner** [rusershamburg/rusershamburg.github.io#19]
#13 

- rusershamburg.org 👍 
- rusers.hamburg 👍 
- hamburgr.org (kurz und prägnant)
- hamburgrusergroup.org (so heißt das Meetup)
- hamburg-r-user-group.org
- r-user-group.hamburg
- rughh.org
- rug.hamburg

**Comment by petermeissner** [comment]
❌ rbind liefert keine Domains und kein Emailhosting

**Comment by henningsway** [comment]
ich mag die ersten beiden besonders. :)

**Comment by petermeissner** [comment]
rusershamburg.org it is .... 
für eine EMailadresse bitte bei info@rusershamburg.org melden.
